SMP-1338: add functions for external redis env and connection string
harness/helm-common pull request #24
Opened 2023-05-24 17:51 UTC by kapilgarg1996

2023-05-25 04:30 UTC, arya-harness requested changes

2023-05-25 05:38 UTC, kapilgarg1996 commented on src/common/templates/_databaseconnections.tpl
> +{{- include "harnesscommon.dbconnection.dbenvuser" (dict "type" $type "secret" $passwordSecret  "userKey" $userKey "variableName" .userVariableName ) }}
we won't be changing lock config ,
for events framework config, different services have different names for environment variables so we will use their respective names

2023-05-25 05:40 UTC, kapilgarg1996 commented on src/common/templates/_databasehelpers.tpl
> +{{- $name := default (printf "%s_USER" $dbType) .variableName }}
```
{{- include "harnesscommon.dbconnection.redisEnv" (dict "context" .Values.global.database.redis "userVariableName" "EVENTS_FRAMEWORK_REDIS_USERNAME" "passwordVariableName" "EVENTS_FRAMEWORK_REDIS_PASSWORD") | indent 12 }}
 ```

2023-05-25 05:42 UTC, kapilgarg1996 commented on src/common/templates/_databaseconnections.tpl
> +{{- $connectionString := (printf "%s://%s" $protocol $firsthost) -}}
currently we only support redis single server or redis sentinel in backend. In SaaS, we are using single server only. So it makes sense to use only 1 host here. 
`args` can be `?db=0` or something like that, but will be empty by default

2023-05-26 07:09 UTC, arya-harness approved these changes

2023-05-26 07:27 UTC, merged